### ISSUE TITLE
Fail to validate the HKID beginning with two alphabets

### ISSUE THREAD

**Issue by musso** [tsekityam/hkid#61]
```
import * as hkid from "hkid";

console.log(hkid.validate("YK1597716"));  // return false, but it's a valid HKID

```

**Comment by tsekityam** [comment]
Hi @musso , thank you for your reporting. However, `YK1597716` is not a valid HKID.

A valid HKID should be
1. starts with known prefix
2. ends withe the right checksum

`YK` is not a known prefix of HKID. According to [this comment from immd](https://accessinfo.hk/en/request/you_guan_xiang_gang_shen_fen_zhe_2#incoming-1451), HKID usually starts with one alphabet only. For some foreigners, HKID may starts with two alphabets, such as `WX`, `XA`, `XB`. And `YK` is not listed.

Do you know if there is anyone have a HKID starts with `YK`? If so, I will add it to the [known prefix list](https://github.com/tsekityam/hkid/blob/401af13022e026a04ffc7bd6f9330955bf2cd307/src/index.ts#L35-L61).

By the way, I am thinking providing an option to disable this strict prefix test (i.e. test checksum only).

**Comment by musso** [comment]
Thanks for the clarification. It's good to provide an option to disable prefix check too. FYI, The sample HKID `YK1597716` is a random number generated from [here](https://pinkylam.me/playground/hkid/ ). Guess it's not a valid sample.
